In [1]:
# Importing pandas libraray to get the access of data in a readable format
import pandas as pd 

In [2]:
# Load the dataset
data = pd.read_csv("spam.tsv",sep='\t',names=['Class','Message'])
data

Class                                            Message
0      ham  I've been searching for the right words to tha...
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...
2      ham  Nah I don't think he goes to usf, he lives aro...
3      ham  Even my brother is not like to speak with me. ...
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!
...    ...                                                ...
5562  spam  This is the 2nd time we have tried 2 contact u...
5563   ham               Will ü b going to esplanade fr home?
5564   ham  Pity, * was in mood for that. So...any other s...
5565   ham  The guy did some bitching but I acted like i'd...
5566   ham                         Rofl. Its true to its name

[5567 rows x 2 columns]

In [3]:
# View the first 8 records of our dataset
data.head(8) 

Class                                            Message
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!
5   ham  As per your request 'Melle Melle (Oru Minnamin...
6  spam  WINNER!! As a valued network customer you have...
7  spam  Had your mobile 11 months or more? U R entitle...

In [4]:
# Summary of the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5567 entries, 0 to 5566
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    5567 non-null   object
 1   Message  5567 non-null   object
dtypes: object(2)
memory usage: 87.1+ KB


In [6]:
# create a column to keep the count of the characters present in each record
data['Length'] = data['Message'].apply(len)

In [7]:
data['Length']

0       196
1       155
2        61
3        77
4        36
       ... 
5562    160
5563     36
5564     57
5565    125
5566     26
Name: Length, Length: 5567, dtype: int64

In [8]:
# view the dataset with the column 'Length' which contains the number of characters present in each mail
data.head(10)

Class                                            Message  Length
0   ham  I've been searching for the right words to tha...     196
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2   ham  Nah I don't think he goes to usf, he lives aro...      61
3   ham  Even my brother is not like to speak with me. ...      77
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
5   ham  As per your request 'Melle Melle (Oru Minnamin...     160
6  spam  WINNER!! As a valued network customer you have...     157
7  spam  Had your mobile 11 months or more? U R entitle...     154
8   ham  I'm gonna be home soon and i don't want to tal...     109
9  spam  SIX chances to win CASH! From 100 to 20,000 po...     136

In [9]:
## The mails are categorised into 2 classes ie., spam and ham. 
# Let's see the count of each class
data.groupby('Class').count()

Message  Length
Class                 
ham       4821    4821
spam       746     746

In [10]:
data['Length'].describe() # to find the max length of the message. 

count    5567.000000
mean       80.450153
std        59.891023
min         2.000000
25%        36.000000
50%        62.000000
75%       122.000000
max       910.000000
Name: Length, dtype: float64

In [11]:
data['Length']==910

0       False
1       False
2       False
3       False
4       False
        ...  
5562    False
5563    False
5564    False
5565    False
5566    False
Name: Length, Length: 5567, dtype: bool

In [12]:
# the message that has the max characters
data[data['Length']==910]['Message']

1080    For me the love should start with attraction.i...
Name: Message, dtype: object

In [13]:
# view the message that has 910 characters in it
data[data['Length']==910]['Message'].iloc[0]

"For me the love should start with attraction.i should feel that I need her every time around me.she should be the first thing which comes in my thoughts.I would start the day and end it with her.she should be there every time I dream.love will be then when my every breath has her name.my life should happen around her.my life will be named to her.I would cry for her.will give all my happiness and take all her sorrows.I will be ready to fight with anyone for her.I will be in love when I will be doing the craziest things for her.love will be when I don't have to proove anyone that my girl is the most beautiful lady on the whole planet.I will always be singing praises for her.love will be when I start up making chicken curry and end up makiing sambar.life will be the most beautiful then.will get every morning and thank god for the day because she is with me.I would like to say a lot..will tell later.."

In [14]:
# View the message that has min characters
data[data['Length']==2]['Message'].iloc[0]

'Ok'

# Text PreProcessing

In [15]:
# creating an object for the target values
dObject = data['Class'].values
dObject

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [16]:
# Lets assign ham as 1
data.loc[data['Class']=="ham","Class"] = 1

In [17]:
# Lets assign spam as 0
data.loc[data['Class']=="spam","Class"] = 0

In [18]:
dObject2=data['Class'].values
dObject2

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [19]:
data.head(8)

Class                                            Message  Length
0     1  I've been searching for the right words to tha...     196
1     0  Free entry in 2 a wkly comp to win FA Cup fina...     155
2     1  Nah I don't think he goes to usf, he lives aro...      61
3     1  Even my brother is not like to speak with me. ...      77
4     1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
5     1  As per your request 'Melle Melle (Oru Minnamin...     160
6     0  WINNER!! As a valued network customer you have...     157
7     0  Had your mobile 11 months or more? U R entitle...     154

In [20]:
# the default list of punctuations
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [21]:
# Why is it important to remove punctuation?

"This message is spam" == "This message is spam."

False

In [22]:
# Let's remove the punctuation

def remove_punct(text):
    text = "".join([char for char in text if char not in string.punctuation])
    return text

data['text_clean'] = data['Message'].apply(lambda x: remove_punct(x))

data.head()

Class                                            Message  Length  \
0     1  I've been searching for the right words to tha...     196   
1     0  Free entry in 2 a wkly comp to win FA Cup fina...     155   
2     1  Nah I don't think he goes to usf, he lives aro...      61   
3     1  Even my brother is not like to speak with me. ...      77   
4     1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36   

                                          text_clean  
0  Ive been searching for the right words to than...  
1  Free entry in 2 a wkly comp to win FA Cup fina...  
2  Nah I dont think he goes to usf he lives aroun...  
3  Even my brother is not like to speak with me T...  
4                  I HAVE A DATE ON SUNDAY WITH WILL

In [23]:
# original text and cleaned text
data.head(8)

Class                                            Message  Length  \
0     1  I've been searching for the right words to tha...     196   
1     0  Free entry in 2 a wkly comp to win FA Cup fina...     155   
2     1  Nah I don't think he goes to usf, he lives aro...      61   
3     1  Even my brother is not like to speak with me. ...      77   
4     1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36   
5     1  As per your request 'Melle Melle (Oru Minnamin...     160   
6     0  WINNER!! As a valued network customer you have...     157   
7     0  Had your mobile 11 months or more? U R entitle...     154   

                                          text_clean  
0  Ive been searching for the right words to than...  
1  Free entry in 2 a wkly comp to win FA Cup fina...  
2  Nah I dont think he goes to usf he lives aroun...  
3  Even my brother is not like to speak with me T...  
4                  I HAVE A DATE ON SUNDAY WITH WILL  
5  As per your request Melle Melle Oru Minnaminun...  
6  WINNER As a valued network customer you have b...  
7  Had your mobile 11 months or more U R entitled...

In [25]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [26]:
# Countvectorizer is a method to convert text to numerical data. 

# Initialize the object for countvectorizer 
CV = CountVectorizer(stop_words="english")

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
# Splitting x and y

xSet = data['text_clean'].values
ySet = data['Class'].values
ySet

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [29]:
# Datatype for y is object. lets convert it into int
ySet = ySet.astype('int')
ySet

array([1, 0, 1, ..., 1, 1, 1])

In [30]:
xSet

array(['Ive been searching for the right words to thank you for this breather I promise i wont take your help for granted and will fulfil my promise You have been wonderful and a blessing at all times',
       'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005 Text FA to 87121 to receive entry questionstd txt rateTCs apply 08452810075over18s',
       'Nah I dont think he goes to usf he lives around here though', ...,
       'Pity  was in mood for that Soany other suggestions',
       'The guy did some bitching but I acted like id be interested in buying something else next week and he gave it to us for free',
       'Rofl Its true to its name'], dtype=object)

# Splitting Train and Test Data

In [31]:
xSet_train,xSet_test,ySet_train,ySet_test = train_test_split(xSet,ySet,test_size=0.2, random_state=10)

In [32]:
xSet_train_CV = CV.fit_transform(xSet_train)
xSet_train_CV

<4453x8159 sparse matrix of type '<class 'numpy.int64'>'
	with 34532 stored elements in Compressed Sparse Row format>

# Training a model

With messages represented as vectors, we can finally train our spam/ham classifier. Now we can actually use almost any sort of classification algorithms. For a variety of reasons, the Naive Bayes classifier algorithm is a good choice.

In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
# Initialising the model
NB = MultinomialNB()

In [37]:
# feed data to the model
NB.fit(xSet_train_CV,ySet_train)

MultinomialNB()

In [36]:
# Let's test CV on our test data
xSet_test_CV = CV.transform(xSet_test)

In [38]:
# prediction for xSet_test_CV

ySet_predict = NB.predict(xSet_test_CV)
ySet_predict

array([1, 1, 1, ..., 1, 1, 1])

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
# Checking accuracy

accuracyScore = accuracy_score(ySet_test,ySet_predict)*100

print("Prediction Accuracy :",accuracyScore)

Prediction Accuracy : 98.29443447037703


# Email Classification Application

In [44]:
msg = input("Enter Message: ") # to get the input message
msgInput = CV.transform([msg]) # 
predict = NB.predict(msgInput)
if(predict[0]==0):
    print("------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------")
else:
    print("---------------------------MESSAGE-SENT-[CHECK-INBOX]------------------------------")

Enter Message: free entry
------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------
